[workspace]
resolver = "2"
members = [
    "cargo-nx",
    "cargo-nx/gen",
    "nx-netloader",
    "nx-object",
]

[workspace.dependencies]
serde = { version = "1.0", default-features = false }
thiserror = { version = "2.0", default-features = false }
tokio = { version = "1.42", default-features = false }
tracing = { version = "0.1.41", default-features = false }
