//! `bin2c` subcommand — convert binary files into C source (alias: `raw2c`).

use std::{
    fs::File,
    io::{self, BufWriter, Write},
    path::PathBuf,
};

use super::identifier::sanitize_identifier;

/// Entry point for the `bin2c` (alias `raw2c`) subcommand.
///
/// Reads each input file, emits one C array block per non-empty file to the
/// configured output (stdout or `--output` file), and optionally writes a
/// matching header with extern declarations when `--header` is provided.
pub fn handle_subcommand(args: Args) -> Result<(), Error> {
    let entries = read_entries(&args.inputs)?;
    write_source(&args, &entries)?;

    if let Some(header_path) = args.header.as_ref() {
        write_header(header_path, &entries)?;
    }

    Ok(())
}

#[derive(clap::Args)]
pub struct Args {
    /// Input binary files
    #[arg(required = true, num_args = 1..)]
    pub inputs: Vec<PathBuf>,

    /// Also write a C header with extern declarations to PATH
    #[arg(short = 'H', long, value_name = "PATH")]
    pub header: Option<PathBuf>,

    /// Write C output to PATH instead of stdout
    #[arg(short = 'o', long, value_name = "PATH")]
    pub output: Option<PathBuf>,
}

/// Errors from the `bin2c` subcommand.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// Failed to read an input file
    #[error("Failed to read input file '{}'", path.display())]
    ReadInput { path: PathBuf, source: io::Error },

    /// Could not derive a valid C identifier from the input filename
    #[error("Cannot derive a valid C identifier from input filename '{}'", path.display())]
    InvalidFileName { path: PathBuf },

    /// Failed to write the C output to stdout
    #[error("Failed to write C output to stdout")]
    WriteStdout(#[source] io::Error),

    /// Failed to write the C output file
    #[error("Failed to write C output file '{}'", path.display())]
    WriteOutputFile { path: PathBuf, source: io::Error },

    /// Failed to write the C header file
    #[error("Failed to write header file '{}'", path.display())]
    WriteHeader { path: PathBuf, source: io::Error },
}

/// A single input file resolved to its sanitized C identifier and contents.
struct Entry {
    name: String,
    bytes: Vec<u8>,
}

/// Read every input path into an [`Entry`], skipping empty files with a warning.
///
/// Returns [`Error::InvalidFileName`] if a path lacks a usable basename or if
/// sanitization yields an empty identifier.
fn read_entries(inputs: &[PathBuf]) -> Result<Vec<Entry>, Error> {
    let mut entries = Vec::with_capacity(inputs.len());

    for path in inputs {
        let basename = path
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or_else(|| Error::InvalidFileName { path: path.clone() })?;

        let name = sanitize_identifier(basename, false)
            .ok_or_else(|| Error::InvalidFileName { path: path.clone() })?;

        let bytes = std::fs::read(path).map_err(|err| Error::ReadInput {
            path: path.clone(),
            source: err,
        })?;

        if bytes.is_empty() {
            tracing::warn!(path = %path.display(), "skipping empty input file");
            continue;
        }

        entries.push(Entry { name, bytes });
    }

    Ok(entries)
}

/// Write all entries to the C source destination (stdout or file).
///
/// Errors are mapped to [`Error::WriteOutputFile`] or [`Error::WriteStdout`]
/// based on which destination was selected.
fn write_source(args: &Args, entries: &[Entry]) -> Result<(), Error> {
    match args.output.as_ref() {
        Some(path) => {
            let file = File::create(path).map_err(|err| Error::WriteOutputFile {
                path: path.clone(),
                source: err,
            })?;
            let mut writer = BufWriter::new(file);
            write_source_to(&mut writer, entries)
                .and_then(|()| writer.flush())
                .map_err(|err| Error::WriteOutputFile {
                    path: path.clone(),
                    source: err,
                })
        }
        None => {
            let stdout = io::stdout();
            let mut writer = BufWriter::new(stdout.lock());
            write_source_to(&mut writer, entries)
                .and_then(|()| writer.flush())
                .map_err(Error::WriteStdout)
        }
    }
}

/// Emit the file preamble followed by one C array block per entry, separated
/// by blank lines for readability.
fn write_source_to<W: Write>(writer: &mut W, entries: &[Entry]) -> io::Result<()> {
    writer.write_all(b"/* Generated by bin2c - please don't edit directly */\n\n")?;

    for (index, entry) in entries.iter().enumerate() {
        if index > 0 {
            writer.write_all(b"\n")?;
        }
        write_source_block(writer, entry)?;
    }

    Ok(())
}

/// Emit `const unsigned char <name>[] = { ... };` plus a `<name>_size` constant
/// for `entry`, formatting bytes as lowercase `0x%02x`, 16 per line.
fn write_source_block<W: Write>(writer: &mut W, entry: &Entry) -> io::Result<()> {
    writeln!(writer, "const unsigned char {}[] = {{", entry.name)?;

    let last_index = entry.bytes.len() - 1;
    for (index, byte) in entry.bytes.iter().enumerate() {
        if index % 16 == 0 {
            writer.write_all(b"\t")?;
        }

        write!(writer, "0x{byte:02x}")?;

        if index != last_index {
            writer.write_all(b",")?;
            if (index + 1) % 16 == 0 {
                writer.write_all(b"\n")?;
            } else {
                writer.write_all(b" ")?;
            }
        }
    }

    writer.write_all(b"\n};\n")?;
    writeln!(
        writer,
        "const unsigned int {}_size = sizeof({});",
        entry.name, entry.name
    )?;

    Ok(())
}

/// Write the optional C header to `path`, mapping io errors to
/// [`Error::WriteHeader`].
fn write_header(path: &PathBuf, entries: &[Entry]) -> Result<(), Error> {
    let file = File::create(path).map_err(|err| Error::WriteHeader {
        path: path.clone(),
        source: err,
    })?;
    let mut writer = BufWriter::new(file);

    write_header_to(&mut writer, entries)
        .and_then(|()| writer.flush())
        .map_err(|err| Error::WriteHeader {
            path: path.clone(),
            source: err,
        })
}

/// Emit `#pragma once` plus one pair of extern declarations per entry
/// (the array itself and its `_size` constant).
fn write_header_to<W: Write>(writer: &mut W, entries: &[Entry]) -> io::Result<()> {
    writer.write_all(
        b"/* Generated by bin2c - please don't edit directly */\n\
          #pragma once\n\n",
    )?;

    for entry in entries {
        writeln!(writer, "extern const unsigned char {}[];", entry.name)?;
        writeln!(writer, "extern const unsigned int {}_size;", entry.name)?;
    }

    Ok(())
}
