name: ci
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          components: clippy
          cache: true
          rustflags: ''

      - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3.4.0
        with:
          crate: cargo-nextest
          version: ^0.9
          locked: true

      ## Build
      - name: check (release)
        run: cargo check --all-features --release

      - name: clippy
        run: cargo clippy --all-features -- -D warnings --force-warn deprecated --force-warn dead-code

      ## Test
      - name: unit-tests
        run: cargo nextest run --all-features

      - name: doc-tests
        run: cargo test --all-features --doc

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          toolchain: nightly
          components: rustfmt
          cache: false

      - run: cargo +nightly fmt --all -- --check

  # Check generated schemas under docs/schemas/ are up to date
  gen-check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          cache: true
          rustflags: ''

      - name: Setup just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: Run code generation
        run: just gen

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            printf "Generated schemas are out of date. Please run 'just gen' and commit the changes.\n"

            printf "\nFiles with changes:\n"
            git status --porcelain

            printf "\nDetailed diff:\n"
            git diff --color=always

            exit 1
          fi
